apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: tejaswiambula/my-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort  # Use LoadBalancer if using a managed cloud service like AWS EKS
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007  # Expose via a specific NodePort
  selector:
    app: my-app
